# Generated by Django 5.2.4 on 2025-07-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
    ]
